print("Thanos llegó a la Tierra exigiendo todas las gemas del infinito y un buen taco al pastor.")
# 2 (Persona 2)
# 3 (Persona 3)
print("El Capitán América suspiró, sacó su escudo y se puso a dirigir el tráfico para evitar más accidentes.")
# 5 (Persona 2)
# 6 (Persona 3)
print("Thanos, confundido por el caos, decidió sentarse en la banqueta a esperar que los Avengers se organizaran.")
# 8 (Persona 2)
# 9 (Persona 3)